#!/bin/bash
set -euo pipefail

theme=Tokyonight-Dark
icon_theme=Papirus-Dark
font="JetBrainsMono Nerd Font Propo"

font_doc=$font
font_mono=$font
gtk3_dir=~/.config/gtk-3.0/
gtk4_dir=~/.config/gtk-4.0/
theme_dir=~/.themes/"$theme"

# remove the previous theme
rm $gtk4_dir/*

# add or overwrite with new theme
gsettings set org.gnome.desktop.wm.preferences button-layout ''
gsettings set org.gnome.desktop.interface gtk-theme "$theme"
gsettings set org.gnome.desktop.interface icon-theme "$icon_theme"
gsettings set org.gnome.desktop.interface font-name "$font"
gsettings set org.gnome.desktop.interface document-font-name "$font_doc"
gsettings set org.gnome.desktop.interface monospace-font-name "$font_mono"
gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"


if [ ! -d $gtk3_dir ]; then
    mkdir "$gtk3_dir"
fi

if [ ! -d $gtk4_dir ]; then
    mkdir "$gtk4_dir"
fi


echo "[Settings]
gtk-theme-name = $theme
gtk-icon-theme-name = $icon_theme
gtk-font-name = $font" > $gtk3_dir/settings.ini


ln -sf "$theme_dir"/gtk-4.0/gtk.css "$gtk4_dir"/gtk.css
ln -sf "$theme_dir"/gtk-4.0/gtk-dark.css "$gtk4_dir"/gtk-dark.css
ln -sf "$theme_dir"/gtk-4.0/assets/ "$gtk4_dir"/assets


if pacman -Q flatpak &> /dev/null; then
    flatpak override --user --filesystem=~/.themes
    flatpak override --user --filesystem=~/.icons
    flatpak override --user --filesystem=xdg-config/gtk-4.0

    flatpak override --user --env GTK_THEME=$theme
    flatpak override --user --env ICON_THEME=$icon_theme
fi

if [ -d ~/.var/app/dev.vencord.Vesktop/config/vesktop/themes/ ]; then
    curl https://raw.githubusercontent.com/refact0r/midnight-discord/refs/heads/master/themes/flavors/midnight-tokyo-night.theme.css -o ~/.var/app/dev.vencord.Vesktop/config/vesktop/themes/midnight-tokyo-night.theme.css
fi
